dist: xenial
sudo: required
language: python
python:
  - 3.7
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
install: "pip install -r requirements.txt"
before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script: HEADLESS=true behave
